# Generated by Django 4.2.5 on 2023-10-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.TextField(
                        blank=True, max_length=250, verbose_name="Название склада"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Описание склада"
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
