# Generated by Django 4.2.5 on 2023-09-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseAmount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.productitem')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse')),
            ],
        ),
    ]
