# Generated by Django 4.2.5 on 2023-09-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0051_remove_productitem_product_productsku_and_more'),
        ('stock', '0002_alter_warehouseamount_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseamount',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.productsku'),
        ),
    ]
