# Generated by Django 4.2.5 on 2023-09-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0003_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='photo_url',
            field=models.ImageField(blank=True, upload_to='images/logo'),
        ),
    ]
