# Generated by Django 4.2.5 on 2023-09-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0004_alter_logo_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='active',
            field=models.BooleanField(blank=True),
        ),
    ]
