# Generated by Django 4.2.5 on 2023-09-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0005_alter_logo_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysystem',
            name='img_url',
            field=models.ImageField(blank=True, upload_to='images/shop_settings/pay_system'),
        ),
        migrations.AddField(
            model_name='socical',
            name='img_url',
            field=models.ImageField(blank=True, upload_to='images/shop_settings/social'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='photo_url',
            field=models.ImageField(blank=True, upload_to='images/shop_settings/logo'),
        ),
    ]
