# Generated by Django 4.2.5 on 2023-09-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0006_paysystem_img_url_socical_img_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='photo_url',
            new_name='logo_url',
        ),
    ]
