# Generated by Django 4.2.5 on 2023-09-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0007_rename_photo_url_logo_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo_url',
            field=models.ImageField(upload_to='images/shop_settings/logo'),
        ),
    ]
