# Generated by Django 4.2.5 on 2023-09-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0008_alter_logo_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysystem',
            name='img_url',
            field=models.ImageField(upload_to='images/shop_settings/pay_system'),
        ),
        migrations.AlterField(
            model_name='socical',
            name='img_url',
            field=models.ImageField(upload_to='images/shop_settings/social'),
        ),
        migrations.AlterField(
            model_name='socical',
            name='link',
            field=models.TextField(max_length=500),
        ),
    ]
