# Generated by Django 4.2.5 on 2023-09-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0009_alter_paysystem_img_url_alter_socical_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='position',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second')], unique=True),
        ),
    ]
