# Generated by Django 4.2.5 on 2023-09-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0013_alter_phone_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='position',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second')], null=True, unique=True),
        ),
    ]
