# Generated by Django 4.2.5 on 2023-10-16 15:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(
                        blank=True, default=True, help_text="If this object is active"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название бренда"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Описание бренда"
                    ),
                ),
                (
                    "img_url",
                    models.ImageField(
                        blank=True,
                        upload_to="images/goods/brands",
                        verbose_name="Лого бренда",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(
                        blank=True, default=True, help_text="If this object is active"
                    ),
                ),
                (
                    "name",
                    models.TextField(max_length=250, verbose_name="Название категории"),
                ),
                (
                    "img_url",
                    models.ImageField(blank=True, upload_to="images/goods/categories"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CharacteristicValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(
                        blank=True, default=True, help_text="If this object is active"
                    ),
                ),
                ("value", models.CharField(max_length=50, verbose_name="Значение")),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ProductSku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(
                        blank=True, default=True, help_text="If this object is active"
                    ),
                ),
                (
                    "sku",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Артикул",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "img_url",
                    models.ImageField(blank=True, upload_to="images/goods/product"),
                ),
                (
                    "characteristics",
                    models.ManyToManyField(
                        to="goods.characteristicvalue", verbose_name="Характеристики"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(
                        blank=True, default=True, help_text="If this object is active"
                    ),
                ),
                (
                    "name",
                    models.TextField(max_length=250, verbose_name="Название продукта"),
                ),
                (
                    "img_url",
                    models.ImageField(blank=True, upload_to="images/goods/product"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.categorie",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "skus",
                    models.ManyToManyField(
                        to="goods.productsku", verbose_name="Артикулы"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Characteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(
                        blank=True, default=True, help_text="If this object is active"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "values",
                    models.ManyToManyField(
                        to="goods.characteristicvalue", verbose_name="Значение"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="categorie",
            name="characteristics",
            field=models.ManyToManyField(
                to="goods.characteristic", verbose_name="Фильтр"
            ),
        ),
    ]
