# Generated by Django 4.2.5 on 2023-09-24 16:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField(default='1', max_length=250)),
                ('title', models.TextField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('img_url', models.ImageField(blank=True, upload_to='images/goods/categories')),
                ('link_url', models.TextField(db_index=True, max_length=255, null=True, unique=True, verbose_name='URL')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default='1', max_length=250)),
                ('title', models.TextField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('img_url', models.ImageField(blank=True, upload_to='images/goods/product')),
                ('link_url', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.categorie')),
                ('property_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.propertyname')),
                ('property_value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.propertyvalue')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.TextField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('img_url', models.ImageField(blank=True, upload_to='images/goods/product')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('product_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.productitem')),
                ('product_property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.property')),
            ],
        ),
    ]
