# Generated by Django 4.2.5 on 2023-10-24 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="brand",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="categorie",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="characteristic",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="characteristicvalue",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="product",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="productsku",
            managers=[],
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Описание товара"
            ),
        ),
        migrations.AddField(
            model_name="productsku",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Описание артикула товара",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Описание бренда"
            ),
        ),
        migrations.AlterField(
            model_name="characteristic",
            name="name",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Название характеристики"
            ),
        ),
        migrations.AlterField(
            model_name="characteristic",
            name="values",
            field=models.ManyToManyField(
                to="goods.characteristicvalue", verbose_name="Значение характеристики"
            ),
        ),
        migrations.AlterField(
            model_name="characteristicvalue",
            name="value",
            field=models.CharField(
                max_length=50, verbose_name="Значение характеристики"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.brand",
                verbose_name="Бренд продукта",
            ),
        ),
        migrations.AlterField(
            model_name="productsku",
            name="characteristics",
            field=models.ManyToManyField(
                to="goods.characteristicvalue", verbose_name="Характеристики товара"
            ),
        ),
        migrations.AlterField(
            model_name="productsku",
            name="sku",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Артикул товара",
            ),
        ),
    ]
