# Generated by Django 4.2.5 on 2023-09-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('category', 'property_name', 'property_value')},
        ),
    ]
