# Generated by Django 4.2.5 on 2023-09-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_productitem_product_productsku_and_more'),
        ('stock', '0002_alter_warehouseamount_product_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductItem',
        ),
    ]
