# Generated by Django 4.2.5 on 2023-09-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_delete_productitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productconfig',
            unique_together={('product_property', 'product_item')},
        ),
    ]
