# Generated by Django 4.2.5 on 2023-09-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_productconfig_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productconfig',
            unique_together={('product_property', 'product_item')},
        ),
    ]
