# Generated by Django 4.2.5 on 2023-09-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_productconfig_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='CategoryCharacteristic',
        ),
        migrations.RenameModel(
            old_name='PropertyValue',
            new_name='CharacteristicName',
        ),
        migrations.RenameModel(
            old_name='PropertyName',
            new_name='CharacteristicValue',
        ),
        migrations.RenameField(
            model_name='characteristicname',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='characteristicvalue',
            old_name='name',
            new_name='value',
        ),
    ]
