# Generated by Django 4.2.5 on 2023-09-28 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_rename_property_categorycharacteristic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycharacteristic',
            name='property_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.characteristicname'),
        ),
        migrations.AlterField(
            model_name='categorycharacteristic',
            name='property_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.characteristicvalue'),
        ),
    ]
