# Generated by Django 4.2.5 on 2023-10-03 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0009_alter_categorycharacteristic_property_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CategoryCharacteristic",
            new_name="Property",
        ),
        migrations.RenameModel(
            old_name="CharacteristicName",
            new_name="PropertyName",
        ),
        migrations.RenameModel(
            old_name="CharacteristicValue",
            new_name="PropertyValue",
        ),
    ]
