


# Generated by Django 4.2.5 on 2023-10-03 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0010_rename_categorycharacteristic_property_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoryonfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(blank=True, default=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.categorie",
                    ),
                ),
                (
                    "product_property",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.property",
                    ),
                ),
            ],
            options={
                "unique_together": {("product_property", "category")},
            },
        ),
    ]
