# Generated by Django 4.2.5 on 2023-10-03 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0011_categoryonfig"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categoryonfig",
            new_name="CategoryPropertyConfig",
        ),
    ]
