# Generated by Django 4.2.5 on 2023-10-03 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0012_rename_categoryonfig_categorypropertyconfig"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="property",
            unique_together={("property_name", "property_value")},
        ),
        migrations.RemoveField(
            model_name="property",
            name="category",
        ),
    ]
