# Generated by Django 4.2.5 on 2023-10-03 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0013_alter_property_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="propertyname",
            unique_together={("name",)},
        ),
    ]
