# Generated by Django 4.2.5 on 2023-10-03 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0014_alter_propertyname_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="propertyname",
            unique_together=set(),
        ),
    ]
