# Generated by Django 4.2.5 on 2023-10-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0016_alter_categorypropertyconfig_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pr_name",
                to="goods.propertyname",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_value",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pr_val",
                to="goods.propertyvalue",
            ),
        ),
    ]
