# Generated by Django 4.2.5 on 2023-10-05 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0017_alter_property_property_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorypropertyconfig",
            name="property_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prop",
                to="goods.propertyname",
            ),
        ),
    ]
