# Generated by Django 4.2.5 on 2023-10-08 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0018_alter_categorypropertyconfig_property_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="property",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="property",
            name="name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_name",
                to="goods.propertyname",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="value",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_value",
                to="goods.propertyvalue",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="property",
            unique_together={("name", "value")},
        ),
        migrations.RemoveField(
            model_name="property",
            name="property_name",
        ),
        migrations.RemoveField(
            model_name="property",
            name="property_value",
        ),
    ]
