# Generated by Django 4.2.5 on 2023-10-08 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0019_alter_property_unique_together_property_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="property",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="property",
            name="property_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pr_name",
                to="goods.propertyname",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_value",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pr_val",
                to="goods.propertyvalue",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="property",
            unique_together={("property_name", "property_value")},
        ),
        migrations.RemoveField(
            model_name="property",
            name="name",
        ),
        migrations.RemoveField(
            model_name="property",
            name="value",
        ),
    ]
