# Generated by Django 4.2.5 on 2023-10-08 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0020_alter_property_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CategoryPropertyConfig",
        ),
    ]
