# Generated by Django 4.2.5 on 2023-10-08 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0021_delete_categorypropertyconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductConfig",
        ),
    ]
