# Generated by Django 4.2.5 on 2023-10-08 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0022_delete_productconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Property",
        ),
        migrations.DeleteModel(
            name="PropertyName",
        ),
        migrations.DeleteModel(
            name="PropertyValue",
        ),
    ]
