# Generated by Django 4.2.5 on 2023-09-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo_url',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
