# Generated by Django 4.2.5 on 2023-09-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_rename_categories_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='categorie',
            name='category_name',
            field=models.TextField(default='1', max_length=250),
        ),
        migrations.AddField(
            model_name='categorie',
            name='img_url',
            field=models.ImageField(blank=True, upload_to='images/goods/categorie'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='link_url',
            field=models.TextField(default='/'),
        ),
    ]
