# Generated by Django 4.2.5 on 2023-09-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_categorie_photo_url_categorie_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='link_url',
            field=models.TextField(blank=True, default=None),
        ),
    ]
