# Generated by Django 4.2.5 on 2023-09-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_categorie_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='link_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
