# Generated by Django 4.2.5 on 2023-09-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_categorie_link_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(default='1', max_length=250)),
                ('title', models.TextField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('img_url', models.ImageField(blank=True, upload_to='images/goods/categories')),
                ('link_url', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
