# Generated by Django 4.2.5 on 2023-09-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_categories_delete_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.TextField(max_length=250),
        ),
    ]
