# Generated by Django 4.2.5 on 2023-09-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_alter_categories_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
