# Generated by Django 4.2.5 on 2023-09-21 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_rename_categories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parrent_category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='goods.category'),
        ),
    ]
