# Generated by Django 4.2.5 on 2023-09-21 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_category_parrent_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parrent_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.category'),
        ),
    ]
