# Generated by Django 4.2.5 on 2023-09-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_rename_category_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='1', max_length=250)),
                ('title', models.TextField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('img_url', models.ImageField(blank=True, upload_to='images/goods/categories')),
                ('link_url', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categorie')),
            ],
        ),
    ]
