# Generated by Django 4.2.5 on 2023-09-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_alter_category_parrent_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parrent_category_id',
            new_name='parrent_category',
        ),
    ]
