# Generated by Django 4.2.5 on 2023-09-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_rename_parrent_category_id_category_parrent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parrent_category',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='goods.category'),
        ),
    ]
