# Generated by Django 4.2.5 on 2023-09-21 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.ImageField(blank=True, upload_to='images/goods/product'),
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.TextField(blank=True, max_length=100, null=True)),
                ('qty_in_stoke', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('img_url', models.ImageField(blank=True, upload_to='images/goods/product')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.product')),
            ],
        ),
    ]
