# Generated by Django 4.2.5 on 2023-09-21 09:13

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(blank=True, default=goods.models.Product.get_translate_name, max_length=250),
        ),
    ]
