# Generated by Django 4.2.5 on 2023-09-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_alter_category_id_alter_category_parrent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parrent_category',
        ),
    ]
