# Generated by Django 4.2.5 on 2023-09-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_variationoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.productitem')),
                ('variation_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.variationoption')),
            ],
        ),
    ]
