# Generated by Django 4.2.5 on 2023-09-21 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_productconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
