# Generated by Django 4.2.5 on 2023-09-21 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0019_productitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='qty_in_stoke',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
