# Generated by Django 4.2.5 on 2023-09-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0020_alter_productitem_qty_in_stoke'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='name',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
