# Generated by Django 4.2.5 on 2023-09-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_productconfiguration'),
        ('goods', '0021_variation_name'),
    ]

    operations = [
    ]
