# Generated by Django 4.2.5 on 2023-09-21 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0021_variation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='variation',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='goods.variation'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='variation_option',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='goods.variationoption'),
        ),
    ]
