# Generated by Django 4.2.5 on 2023-09-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0023_delete_productconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='qty_in_stoke',
        ),
    ]
