# Generated by Django 4.2.5 on 2023-09-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0024_remove_productitem_qty_in_stoke'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='name',
            field=models.TextField(blank=True, default='1', max_length=250),
        ),
        migrations.AddField(
            model_name='productitem',
            name='title',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
