# Generated by Django 4.2.5 on 2023-09-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0025_productitem_name_productitem_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variation',
            new_name='Property',
        ),
    ]
