# Generated by Django 4.2.5 on 2023-09-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0026_rename_variation_property'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='ProductProperty',
        ),
    ]
