# Generated by Django 4.2.5 on 2023-09-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0027_rename_property_productproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValueProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.AddField(
            model_name='productproperty',
            name='value',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='name',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
