# Generated by Django 4.2.5 on 2023-09-22 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0028_nameproperty_valueproperty_productproperty_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='goods.nameproperty'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='value',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='goods.valueproperty'),
        ),
    ]
