# Generated by Django 4.2.5 on 2023-09-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0030_alter_productproperty_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductProperty',
            new_name='PropertyProduct',
        ),
        migrations.RenameModel(
            old_name='ValueProperty',
            new_name='PropertyValue',
        ),
    ]
