# Generated by Django 4.2.5 on 2023-09-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0031_rename_productproperty_propertyproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationoption',
            name='variation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
