# Generated by Django 4.2.5 on 2023-09-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0032_alter_variationoption_variation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyValue',
            new_name='ValueProperty',
        ),
    ]
