# Generated by Django 4.2.5 on 2023-09-22 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0033_rename_propertyvalue_valueproperty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyproduct',
            name='name',
        ),
        migrations.AddField(
            model_name='propertyproduct',
            name='property_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.nameproperty'),
        ),
    ]
