# Generated by Django 4.2.5 on 2023-09-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0035_remove_propertyproduct_value_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NameProperty',
            new_name='PropertyName',
        ),
    ]
