# Generated by Django 4.2.5 on 2023-09-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0036_rename_nameproperty_propertyname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValueProperty',
            new_name='PropertyValue',
        ),
    ]
