# Generated by Django 4.2.5 on 2023-09-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0037_rename_valueproperty_propertyvalue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyProduct',
            new_name='Property',
        ),
    ]
