# Generated by Django 4.2.5 on 2023-09-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0038_rename_propertyproduct_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='categorie',
        ),
    ]
