# Generated by Django 4.2.5 on 2023-09-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0040_property_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productconfig',
            name='variation_option',
        ),
    ]
