# Generated by Django 4.2.5 on 2023-09-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0041_remove_productconfig_variation_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='productconfig',
            name='product_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.property'),
        ),
        migrations.AlterField(
            model_name='productconfig',
            name='product_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.productitem'),
        ),
    ]
