# Generated by Django 4.2.5 on 2023-09-22 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0042_productconfig_product_property_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationOption',
        ),
    ]
