# Generated by Django 4.2.5 on 2023-09-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0043_delete_variationoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='title',
        ),
    ]
