# Generated by Django 4.2.5 on 2023-09-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0044_remove_productitem_name_remove_productitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
