# Generated by Django 4.2.5 on 2023-09-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0045_categorie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='slug',
        ),
    ]
