# Generated by Django 4.2.5 on 2023-09-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0046_remove_categorie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='link_url',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
