# Generated by Django 4.2.5 on 2023-09-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0047_alter_categorie_link_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='link_url',
            new_name='slug',
        ),
    ]
