# Generated by Django 4.2.5 on 2023-09-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0048_rename_link_url_categorie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.TextField(db_index=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
