# Generated by Django 4.2.5 on 2023-09-23 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0049_alter_categorie_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='slug',
            new_name='link_url',
        ),
    ]
