# Generated by Django 4.2.5 on 2023-09-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_warehouseamount_product_item'),
        ('goods', '0051_remove_productitem_product_productsku_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductItem',
        ),
    ]
