# Generated by Django 4.2.5 on 2023-09-24 16:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0052_delete_productitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsku',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.TextField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('img_url', models.ImageField(blank=True, upload_to='images/goods/product')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.product')),
            ],
        ),
        migrations.AlterField(
            model_name='productconfig',
            name='product_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.productitem'),
        ),
    ]
