# Generated by Django 4.2.5 on 2023-09-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_warehouseamount_product_item'),
        ('goods', '0053_remove_productsku_product_productitem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSku',
        ),
    ]
