# Generated by Django 4.2.5 on 2023-09-21 12:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0020_alter_productitem_qty_in_stoke'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=250)),
                ('discount_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateTimeField(verbose_name='дата начала акции')),
                ('end_date', models.DateTimeField(verbose_name='дата завершения акции')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categorie')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.promotion')),
            ],
        ),
    ]
