# Generated by Django 4.2.5 on 2023-09-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncategory',
            name='name',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
